# General configuration

set-option -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",xterm-256color:RGB"

set -g set-clipboard on

# keep backward compatible
if-shell 'tmux set -g allow-passthrough on 2>/dev/null' ''

set-option -g history-limit 10000
setw -g mode-keys vi

if-shell "test -f /bin/zsh" \
    "set-option -g default-shell /bin/zsh" \
    "set-option -g default-shell /bin/bash"

set-hook -g after-new-window 'set -w @cwd_sync_panes "off"'

# Theme (pane borders, status bar, window list)
source-file "${DOTFILES_HOME}/tmux/tmux.theme.conf"

# Key binding
source-file "${DOTFILES_HOME}/tmux/tmux.keybinding.conf"

# >> tpm installation >>

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# tmux.conf is sourced with source-file (if-shell)
set -g @tpm_plugins 'tmux-plugins/tpm tmux-plugins/tmux-sensible'

# << tpm installation <<

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run-shell -b "${DOTFILES_HOME}/modules/tpm/tpm"
